- task: FlutterInstall@0
  inputs:
    channel: 'stable'
    version: 'latest'
- task: FlutterBuild@0
  inputs:
    target: 'apk'
    projectDirectory: '.'
    debugMode: true
    apkTargetPlatform: 'android-arm64'