steps:
- task: FlutterInstall@0
  inputs:
    channel: 'stable'
    version: 'custom'
    customVersion: '1.7.8+hotfix.4'
- task: FlutterBuild@0
  inputs:
    target: 'apk'
    projectDirectory: '.'
    debugMode: true
    apkTargetPlatform: 'android-arm64'