name: rits_client
description: Advisory Studio Demo Application
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: 0.12.0+1
  oauth2: 1.2.3
  datetime_picker_formfield: 0.1.8
  equatable: 0.2.3
  #flutter_bloc: 3.2.0
  sealed_flutter_bloc: 6.0.0
  rxdart: 0.23.0
  path_provider: any
  sqflite: 1.1.0
  permission_handler: 3.1.0
  device_info: 0.4.0+2
  font_awesome_flutter: 8.8.1
  provider: ^4.1.3
  memoize: 2.0.0
  logging_appenders: 0.4.1
  flutter_inappwebview: 3.1.0
  flutter_downloader: 1.4.4
  android_intent: 0.3.7+2
  badges: 1.1.1
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  flutter_pdf_viewer:
    # path: ../flutter_pdf_viewer
    git:
      url: https://github.com/Skyggedans/flutter_pdf_viewer.git
  rw_speech_recognizer:
    git:
      url: https://github.com/Skyggedans/rw_speech_recognizer.git
  rw_camera:
    git:
      url: https://github.com/Skyggedans/rw_camera.git
  rw_barcode_reader:
    git:
      url: https://github.com/Skyggedans/rw_barcode_reader.git
  rw_help:
    git:
      url: https://github.com/Skyggedans/rw_help.git
  rw_movie:
    path: ../rw_movie
    # git:
    #   url: https://github.com/Skyggedans/rw_movie.git
  flutter_webview_plugin:
    git:
      url: https://github.com/Skyggedans/flutter_webview_plugin

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/

  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto/Roboto-Black.ttf
          weight: 900
